In [1]:
import pandas as pd
data = pd.Series([10,20,30,40])  
print(data)

0    10
1    20
2    30
3    40
dtype: int64

In [2]:
data = pd.Series([10,20,30],index=["x","y","z"])
print(data)

x    10
y    20
z    30
dtype: int64

In [3]:
data = {
    "Name": ["Ram", "Vani"],
    "Age": [20,25 ]
}

df = pd.DataFrame(data)
print(df)
print("\n")
#print(df.Name) #  or df["Name"]   # access based on col

print(df.loc[0]) # or df.loc[0,"col_Name"]  # 0th-row, Particular Col    #acess base on row

#print(df.loc[1])

   Name  Age
0   Ram   20
1  Vani   25


Name    Ram
Age      20
Name: 0, dtype: object

In [14]:
df=pd.read_csv(""C:\Users\RVUW251\Desktop\hi.txt"")
print(df)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1054651529.py, line 1)

In [5]:
df.isnull()

    Name    Age
0  False  False
1  False  False

In [6]:
df.dropna()  # remove the missing data

   Name  Age
0   Ram   20
1  Vani   25

In [11]:
# basic statistics method
print(df["Marks"].mean())
print(df.Marks.sum())
print(df.Marks.min())
print(df.Marks.max())
print(df.Marks.count())

KeyError: 'Marks'